version: '3.9'
services:
  manager:
    build: ./manager
    container_name: tu-nas-manager
    # Eliminamos el mapeo de puerto 80 del host para que lo use el proxy
    expose:
      - "80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - manager_data:/data
    restart: unless-stopped
    networks:
      - control
      - apps

  ui:
    build: ./ui
    container_name: tu-nas-ui
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - apps

  proxy:
    build: ./proxy
    container_name: tu-nas-proxy
    ports:
      - "80:80"
    volumes:
      - /opt/tu-nas/proxy/conf.d:/etc/nginx/conf.d
    restart: unless-stopped
    depends_on:
      - manager
      - ui
    networks:
      - apps

  agent:
    build: ./agent
    container_name: tu-nas-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MANAGER_URL=http://manager:80
      - NODE_TOKEN=tu-token-secreto
    restart: unless-stopped
    networks:
      - control

networks:
  control:
    internal: true
  apps:
    driver: bridge

volumes:
  manager_data:
