worker_processes 1;
events { worker_connections 1024; }
http {
  server {
    listen 80;
    server_name _;

    # Frontend por defecto
    location / {
      proxy_pass http://ui:3000;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # API redirigida al manager
    location /api {
      proxy_pass http://manager:80;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    # Sockets (para tiempo real)
    location /socket.io {
      proxy_pass http://manager:80;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
    }
  }
  include /etc/nginx/conf.d/*.conf;
}
